In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix, classification_report
from sklearn.preprocessing import Normalizer, MaxAbsScaler, StandardScaler, OneHotEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

In [17]:
SEED = 42
TARGET = "Trend"

df = pd.read_csv("Chevy_US_Data.csv")

df["Trend"] = (df["YOY Change"] > 0).astype(int)

y = df[TARGET].to_numpy(dtype=np.float64)
X_df = df.drop(columns=[TARGET])

test_size = 0.15
val_size = 0.15

X_train, X_test, y_train, y_test = train_test_split(X_df, y, test_size=test_size, random_state=SEED)


val_fraction = val_size / (1.0 - test_size)

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=val_fraction, random_state=SEED)




from pandas.api.types import is_numeric_dtype


numeric_features = [c for c in X_df.columns if is_numeric_dtype(X_df[c])]
categorical_features = [c for c in X_df.columns if c not in numeric_features]

preprocessor = ColumnTransformer([
    ("num", Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scale", StandardScaler())
    ]), numeric_features),
    ("cat", Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ]), categorical_features)
])

# For K Nearest Neighbors

knn_pipe = Pipeline(steps=[
    ("pre", preprocessor),
    ("knn", KNeighborsClassifier(
        n_neighbors=3,
        metric="euclidean",
        algorithm="auto"
    ))
])



#Start with k=3

knn_pipe.fit(X_train, y_train)


# Evaluate on Validation Data

y_val_pred = knn_pipe.predict(X_val)

acc = accuracy_score(y_val, y_val_pred)
prec, rec, f1, _ = precision_recall_fscore_support(y_val, y_val_pred, average="binary")


print()
print()
print()
print("K = 3")
print()
print()
print()


print("Validation Accuracy:", acc)
print("Validation Precision:", prec)
print("Validation F1:", f1)
print("Classification Report: \n", classification_report(y_val, y_val_pred))
print("Confusion Matrix: \n", confusion_matrix(y_val, y_val_pred))



# Now we do k = 5

k = 5

knn_pipe.set_params(knn__n_neighbors=k)


knn_pipe.fit(X_train, y_train)


# Evaluate on Validation Data


y_val_pred = knn_pipe.predict(X_val)


acc = accuracy_score(y_val, y_val_pred)
prec, rec, f1, _ = precision_recall_fscore_support(y_val, y_val_pred, average="binary")


print()
print()
print()
print("K = 5")
print()
print()
print()

print("Validation Accuracy:", acc)
print("Validation Precision:", prec)
print("Validation F1:", f1)
print("Classification Report: \n", classification_report(y_val, y_val_pred))
print("Confusion Matrix: \n", confusion_matrix(y_val, y_val_pred))


print(knn_pipe.get_params())




# Now we do k = 7

k = 7

knn_pipe.set_params(knn__n_neighbors=k)


knn_pipe.fit(X_train, y_train)


# Evaluate on Validation Data


y_val_pred = knn_pipe.predict(X_val)


acc = accuracy_score(y_val, y_val_pred)
prec, rec, f1, _ = precision_recall_fscore_support(y_val, y_val_pred, average="binary")

print()
print()
print()
print("K = 7")
print()
print()
print()

print("Validation Accuracy:", acc)
print("Validation Precision:", prec)
print("Validation F1:", f1)
print("Classification Report: \n", classification_report(y_val, y_val_pred))
print("Confusion Matrix: \n", confusion_matrix(y_val, y_val_pred))




K = 3



Validation Accuracy: 0.6666666666666666
Validation Precision: 0.5
Validation F1: 0.6666666666666666
Classification Report: 
               precision    recall  f1-score   support

         0.0       1.00      0.50      0.67         2
         1.0       0.50      1.00      0.67         1

    accuracy                           0.67         3
   macro avg       0.75      0.75      0.67         3
weighted avg       0.83      0.67      0.67         3

Confusion Matrix: 
 [[1 1]
 [0 1]]



K = 5



Validation Accuracy: 0.6666666666666666
Validation Precision: 0.5
Validation F1: 0.6666666666666666
Classification Report: 
               precision    recall  f1-score   support

         0.0       1.00      0.50      0.67         2
         1.0       0.50      1.00      0.67         1

    accuracy                           0.67         3
   macro avg       0.75      0.75      0.67         3
weighted avg       0.83      0.67      0.67         3

Confusion Matrix: 
 [[1 1]
 [0 1]]
{'

In [18]:
# For Naive Bayes


nb_pipe = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("nb", GaussianNB())
])



nb_pipe.fit(X_train, y_train)


y_val_pred = nb_pipe.predict(X_val)


acc = accuracy_score(y_val, y_val_pred)
prec, rec, f1, _ = precision_recall_fscore_support(y_val, y_val_pred, average="binary")

print()
print()
print()
print("Naive Bayes")
print()
print()
print()

print("Validation Accuracy:", acc)
print("Validation Precision:", prec)
print("Validation F1:", f1)
print("Classification Report: \n", classification_report(y_val, y_val_pred))
print("Confusion Matrix: \n", confusion_matrix(y_val, y_val_pred))









Naive Bayes



Validation Accuracy: 0.6666666666666666
Validation Precision: 0.5
Validation F1: 0.6666666666666666
Classification Report: 
               precision    recall  f1-score   support

         0.0       1.00      0.50      0.67         2
         1.0       0.50      1.00      0.67         1

    accuracy                           0.67         3
   macro avg       0.75      0.75      0.67         3
weighted avg       0.83      0.67      0.67         3

Confusion Matrix: 
 [[1 1]
 [0 1]]
